#Optional - The name of the workflow as it will appear in the Actions tab of the GitHub repository.
name: Cypress Tests
#Specify the event that automatically triggers the workflow file. This example uses the push event,
#so that the jobs run every time someone pushes a change to the repository. You can set up the workflow
#to only run on certain branches, paths, or tags. 
on: [push]
#A job is a set of steps that execute on the same runner. 
#By default, a workflow with multiple jobs will run those jobs in parallel. You can also configure a workflow to run jobs sequentially.
jobs:
  #Job Name
  cypress-run:
    #Configures the job to run on an Ubuntu Linux runner. This means that the job will execute on a fresh virtual machine hosted by GitHub.
    runs-on: ubuntu-latest
    #Groups together all the steps that run in the cypress run job
    steps:
      #The uses keyword tells the job to retrieve v2 of the community action named actions/checkout@v2.
      #This is an action that checks out your repository and downloads it to the runner, allowing you to
      #run actions against your code (such as testing tools). You must use the checkout action any time
      #your workflow will run against the repository's code or you are using an action defined in the repository.
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
